#Especifica la version de node dada en los
#contenedores de docker hub
FROM node:18
# crea el directorio donde estara la aplicacion
# dentro del contenedor (que es linux)
RUN mkdir -p /home/app
# Descargar y ejecutar nodemon
RUN npm i -g nodemon
# Asignamos un directorio de trabajo
WORKDIR /home/app
# Puerto en el que sera accesible nuestro contenedor
# dentro del sistema operativo virtual (que es linux)
EXPOSE 3000
# Comandos que hay que ejecutar para correr la app
# se especifica el comando, y la ruta completa ya no es
# necesaria por que ya se declaro en workdir
CMD ["nodemon", "index.js"]